#!/usr/bin/env node
/*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
	distributed with this work for additional information
   	regarding copyright ownership.  The ASF licenses this file
	to you under the Apache License, Version 2.0 (the
	"License"); you may not use this file except in compliance
	with the License.  You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing,
	software distributed under the License is distributed on an
	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
	KIND, either express or implied.  See the License for the
	specific language governing permissions and limitations
	under the License.
*/


pluginArtifactName = process.argv[2]; // the file name of the .so that is generated in the device/simulator folders
srcDir = process.argv[3]; // directory that contains the native plugin code
destDir = process.argv[4]; // directory that contains the built .so dirs

var fs            = require('fs'),
    shell         = require('shelljs'),
    config        = require('./config');

function setup(){
    shell.rm('-rf','build/*');
    shell.cp('-r', 'bin/*', 'build');
    shell.cp('-r', srcDir, 'build');
}

function build(){
    console.log('Building...');
    shell.exec('cd build && source ' + config.bb10_sdk_path + '/bbndk-env.sh && make clean && make all', {silent: true});
    console.log('Done building');
}

function distribute(){
    console.log('Packaging...');
    shell.exec('cd build && mkdir device && mkdir simulator && cp arm/so.le-v7-g/*.so device && cp x86/so-g/*.so simulator');
    console.log('Done packaging');
}

if(process.argv.length < 2){
    
}
setup();
build();
distribute();

